spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/ddudu
    username: ddudu
    password: ddudulocal
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: true
    locations: classpath:db/migration, classpath:db/data
jwt:
  secret-key: NDaXzFcHzbqw+YWo3jIUViccHL9a3ImaeCTJvQSX7VDyjJK+nSdP/iHWGnusLrmpZyC11SwKiNe99X3WPqKYtw==
  expired-after: 15
logging:
  threshold:
    file: ERROR
  file:
    name: logs/ddudu.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/ddudu.%d{yyyy-MM-dd}.%i.log
      max-file-size: 1MB
      total-size-cap: 5MB
