name: 개발 서버 배포 자동화

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  detect:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      infra_changed: ${{ steps.infra_filter.outputs.infra }}
    steps:
      - name: 체크아웃
        uses: actions/checkout@v6

      - name: Infra 변경사항 감지
        id: infra_filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            infra:
              - 'terraform/dev/**'
              - 'terraform/modules/**'
  infra_update:
    needs: detect
    if: needs.detect.outputs.infra_changed == 'true'
    uses: ./.github/workflows/infra-pipeline.yaml
    with:
      env: dev
      ecr_repository_name: modoo/dev/spring-app
      ecr_repository_tag_name: modoo-dev-spring-app
      infra_update_enabled: true
    secrets: inherit

  dev_deploy:
    needs: [ detect, infra_update ]
    if: always() && needs.detect.result == 'success' && (needs.infra_update.result == 'success' || needs.infra_update.result == 'skipped')
    uses: ./.github/workflows/deploy-pipeline.yaml
    with:
      env: dev
      ecr_repository_name: modoo/dev/spring-app
      ecr_repository_tag_name: modoo-dev-spring-app
      deployment_enabled: true
    secrets: inherit
