name: 개발 서버 배포 자동화

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  detect:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      infra_changed: ${{ steps.infra_filter.outputs.infra }}
      infra_shared_changed: ${{ steps.infra_shared_filter.outputs.infra_shared }}
    steps:
      - name: 체크아웃
        uses: actions/checkout@v6

      - name: Infra 변경사항 감지
        id: infra_filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            infra:
              - 'terraform/dev/**'
              - 'terraform/modules/**'

      - name: Infra 공통 환경 변경사항 감지
        id: infra_shared_filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            infra_shared:
              - 'terraform/shared/**'

  infra_update:
    needs: detect
    if: needs.detect.outputs.infra_changed == 'true' || needs.detect.outputs.infra_shared_changed == 'true'
    uses: ./.github/workflows/infra-pipeline.yaml
    with:
      env: dev
      ecr_repository_name: modoo/dev/spring-app
      ecr_repository_tag_name: modoo-dev-spring-app
      infra_update_enabled: ${{ needs.detect.outputs.infra_changed == 'true' }}
      infra_shared_update_enabled: ${{ needs.detect.outputs.infra_shared_changed == 'true' }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      SUBMODULES_SECRET: ${{ secrets.SUBMODULES_SECRET }}
      TF_VAR_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
      TF_VAR_RDS_DB_NAME: ${{ secrets.DEV_DB_NAME }}
      TF_VAR_RDS_USERNAME: ${{ secrets.DEV_DB_USERNAME }}

  dev_deploy:
    needs: [detect, infra_update]
    if: always() && needs.detect.result == 'success' && (needs.infra_update.result == 'success' || needs.infra_update.result == 'skipped')
    uses: ./.github/workflows/deploy-pipeline.yaml
    with:
      env: dev
      ecr_repository_name: modoo/dev/spring-app
      ecr_repository_tag_name: modoo-dev-spring-app
      deployment_enabled: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      SUBMODULES_SECRET: ${{ secrets.SUBMODULES_SECRET }}
      TF_VAR_DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
      TF_VAR_RDS_DB_NAME: ${{ secrets.DEV_DB_NAME }}
      TF_VAR_RDS_USERNAME: ${{ secrets.DEV_DB_USERNAME }}
