name: 개발 서버 배포 자동화

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  dev-deploy:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/cd-pipeline.yaml
    with:
      env: dev
      task-definition: .aws/dev-task-definition.json
      ecs-container-name: ddudu-dev-ecs-container
      ecs-service: ddudu-dev-ecs-service
      ecs-cluster: ddudu-dev-ecs-cluster
      alimi: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      SUBMODULES_SECRET: ${{ secrets.SUBMODULES_SECRET }}
