name: 개발 서버 배포 자동화

on:
  push:
    branches:
      - main

jobs:
  dev-deploy:
    uses: ./.github/workflows/cd-pipeline.yaml
    with:
      env: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      SUBMODULES_SECRET: ${{ secrets.SUBMODULES_SECRET }}
